### PR TITLE
BUG: fix huge errors in Tiles test

### LINKED ISSUE #20: Fix files test translation

### PR DESCRIPTION
**Pull request by dzenanz**
PhaseCorrelationImageRegistrationMethod has a symmetry around the image middle.
So pass fixed and moving images to PhaseCorrelationOptimizer so it can choose
the proper quadrant which minimizes the overall translation.

Also update *Files test to take advantage of modifications, and update its ground truth. Now it is within one pixel.

Closes #20.

### CODE REVIEW

**Comment by dzenanz** [comment]
[itkMockMontageTest.zip](https://github.com/InsightSoftwareConsortium/ITKMontage/files/1834259/itkMockMontageTest.zip)
Average per-registration translation error for all coordinates: 56.4568
Previously this was approximately 500.

File: include/itkMaxPhaseCorrelationOptimizer.hxx [hunk 1]
```diff
@@ -75,22 +77,23 @@ MaxPhaseCorrelationOptimizer<TRegistrationMethod>
...
+  const typename ImageType::SizeType size = input->GetLargestPossibleRegion().GetSize();
+  const typename ImageType::SpacingType spacing = input->GetSpacing();
+  const typename ImageType::PointType fixedOrigin = fixed->GetOrigin();
+  const typename ImageType::PointType movingOrigin = moving->GetOrigin();
 
   for( unsigned int i = 0; i < ImageDimension; ++i )
     {
-    if ( index[i] > Math::floor( size[i] / 2.0 ) )
+    OffsetScalarType directOffset = (movingOrigin[i] - fixedOrigin[i]) - 1 * spacing[i] * index[i];
+    OffsetScalarType wrapMIOffset = (movingOrigin[i] - fixedOrigin[i]) - 1 * spacing[i] * (index[i] - IndexValueType(size[i]));
```
Comment (thewtex) [inline include/itkMaxPhaseCorrelationOptimizer.hxx]: `MI` means "max index"? Please sio (spell it out ;-) )

Comment (dzenanz) [reply include/itkMaxPhaseCorrelationOptimizer.hxx]: I meant it as a Middle_of_Image, but what I was actually trying it to make it align with the line above, to make it easy to stop the difference. I now renamed the variable to `mirrorOffset`.
